[project]
name = "sakila"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.0",
    "aiosql>=13.4",
    "glootil>=0.2.3"
]

